v0.2.0 updates

diff --git a/tm/eqliscsi/clone b/tm/eqliscsi/clone
--- a/tm/eqliscsi/clone
+++ b/tm/eqliscsi/clone
@@ -19,7 +19,7 @@
 # limitations under the License.                                             #
 #--------------------------------------------------------------------------- #
 
-# clone fe:SOURCE host:remote_system_ds/disk.i size vmid dsid
+# clone fe:SOURCE host:remote_system_ds/disk.i vm_id ds_id
 #   - fe is the front-end hostname
 #   - SOURCE is the path of the disk image in the form DS_BASE_PATH/disk
 #   - host is the target host to deploy the VM
@@ -41,22 +41,22 @@ fi
 
  . $TMCOMMON
 
+EQL_MAD_DEBUG=1
 TM_PATH=$(dirname $0)
 source ${TM_PATH}/../../datastore/eqliscsi/eqliscsi.conf
 source ${TM_PATH}/../../scripts_eqliscsi.sh
 
-SRC_PATH=`arg_path $SRC`
 
 #-------------------------------------------------------------------------------
 # Get EQL vars from datastore/image
 #-------------------------------------------------------------------------------
+# Get disk id from DST path
+DST_PATH=`arg_path $DST`
+DISK_ID=$(echo "$DST_PATH" | $AWK -F. '{print $NF}')
+
 XPATH="${TM_PATH}/../../datastore/xpath.rb --stdin"
 
 unset i XPATH_ELEMENTS
-
-# Get datastore/image data from VM disk
-DISK_ID=$(echo "$SRC_PATH" | $AWK -F. '{print $NF}')
-
 while IFS= read -r -d '' element; do
     XPATH_ELEMENTS[i++]="$element"
 done < <(onevm show -x $VMID| $XPATH \
@@ -66,9 +66,8 @@ done < <(onevm show -x $VMID| $XPATH \
 SRC_DSID="${XPATH_ELEMENTS[0]}"
 SRC_IMID="${XPATH_ELEMENTS[1]}"
 
-unset i XPATH_ELEMENTS
-
 # Get EQL vars from datastore SRC_DSID
+unset i XPATH_ELEMENTS
 while IFS= read -r -d '' element; do
     XPATH_ELEMENTS[i++]="$element"
 done < <(onedatastore show -x $SRC_DSID| $XPATH \
@@ -97,17 +96,16 @@ EQL_MULTIHOST="${XPATH_ELEMENTS[6]:-$EQL_MULTIHOST}"
 EQL_SECURITY_ACCESS="${XPATH_ELEMENTS[7]:-"$EQL_SECURITY_ACCESS"}"
 
 #-------------------------------------------------------------------------------
-# Set src iqn device dst path and dir
+# Set src volume device dst path and dir
 #-------------------------------------------------------------------------------
 
-SRC_IQN="$(eql_src_get_iqn $SRC)"
-SRC_VOLUME="$(eql_src_get_volume $SRC)"
+SRC_VOLUME=$(eql_src_get_volume $SRC)
 
 DST_PATH=`arg_path $DST`
 DST_HOST=`arg_host $DST`
 DST_DIR=`dirname $DST_PATH`
 
-DST_VOLUME=$SRC_VOLUME-$VMID
+DST_VOLUME="${SRC_VOLUME}-${VMID}"
 DST_DEV="$EQL_BASE_DEVICE/$DST_VOLUME"
 
 #-------------------------------------------------------------------------------
@@ -115,14 +113,14 @@ DST_DEV="$EQL_BASE_DEVICE/$DST_VOLUME"
 #-------------------------------------------------------------------------------
 
 # Remote volume cloning on Equallogic (returns IQN)
-log "Cloning volume $SRC_VOLUME on $EQL_HOST to $DST_VOLUME"
+eql_log "Cloning volume $SRC_VOLUME on $EQL_HOST to $DST_VOLUME"
 DST_IQN=$(eqladm_target_clone $SRC_VOLUME $DST_VOLUME "Clone $VMID of $SRC_VOLUME")
-ERROR=$?
-if [ "$ERROR" -ne 0 ]; then
-    log_error "Error cloning from volume $SRC_VOLUME to $DST_VOLUME on $EQL_HOST $SRC_IQN"
+RC=$?
+if [ "$RC" -ne 0 ]; then
+    eql_error_message "Error cloning from volume $SRC_VOLUME to $DST_VOLUME on $EQL_HOST"
     exit 1
 fi
-log "Cloned image $SRC_VOLUME to $DST_VOLUME"
+eql_log "Cloned image $SRC_VOLUME to $DST_VOLUME"
 
 #-------------------------------------------------------------------------------
 # Discover target, login and link volume to device
@@ -134,20 +132,26 @@ DISCOVER_CMD=$(cat <<EOF
     mkdir -p $DST_DIR
     $SUDO $(eqliscsi_discovery)
     $SUDO $(eqliscsi_login "$DST_IQN")
-    ERROR=\$?
-    if [ "\$ERROR" -ne 0 ]; then
-	exit \$ERROR
+    RC=\$?
+    if [ "\$RC" -ne 0 ]; then
+	exit \$RC
     fi
-    # poll
-    while [ ! -L "$DST_DEV" ]; do
-	sleep 1
+    # poll 10 secs for iSCSI device
+    x=0
+    while [ "\$x" -lt 10 -a ! -L "$DST_DEV" ]; do
+        x=\$((x+1))
+        sleep 1
     done
-    ln -sf "$DST_DEV" "$DST_PATH"
+    if [ -L "$DST_DEV" ]; then
+        ln -sf "$DST_DEV" "$DST_PATH"
+    else
+        echo "iSCSI device "$DST_DEV" not found on time"
+        exit 1
+    fi
 EOF
 )
 
-eql_ssh_exec_and_log "$DST_HOST" "$DISCOVER_CMD" \
-        "Error logging in $DST_IQN at $DST_HOST or linking $DST_DEV to $DST_PATH" \
-	"exit"
+ssh_exec_and_log "$DST_HOST" "$DISCOVER_CMD" "Error logging in $DST_IQN at $DST_HOST or linking $DST_DEV to $DST_PATH"
+eql_log "Logged in $DST_VOLUME at $DST_HOST"
 
 exit 0
diff --git a/tm/eqliscsi/delete b/tm/eqliscsi/delete
--- a/tm/eqliscsi/delete
+++ b/tm/eqliscsi/delete
@@ -38,6 +38,7 @@ fi
 
 . $TMCOMMON
 
+EQL_MAD_DEBUG=1
 TM_PATH=$(dirname $0)
 source ${TM_PATH}/../../datastore/eqliscsi/eqliscsi.conf
 source ${TM_PATH}/../../scripts_eqliscsi.sh
@@ -52,13 +53,11 @@ DST_HOST=`arg_host $DST`
 #-------------------------------------------------------------------------------
 # Get IQN information and EQL vars
 #-------------------------------------------------------------------------------
-
 DISK_ID=$(echo "$DST_PATH" | $AWK -F. '{print $NF}')
 
 XPATH="${TM_PATH}/../../datastore/xpath.rb --stdin"
 
 unset i XPATH_ELEMENTS
-
 while IFS= read -r -d '' element; do
     XPATH_ELEMENTS[i++]="$element"
 done < <(onevm show -x $VMID| $XPATH \
@@ -67,7 +66,7 @@ done < <(onevm show -x $VMID| $XPATH \
                     /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/DATASTORE_ID \
                     /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/IMAGE_ID)
 
-SRC="${XPATH_ELEMENTS[0]}"
+EQL_VOLUME="$(eql_src_get_volume ${XPATH_ELEMENTS[0]})"
 PERSISTENT="${XPATH_ELEMENTS[1]}"
 DSID="${XPATH_ELEMENTS[2]}"
 IMID="${XPATH_ELEMENTS[3]}"
@@ -88,20 +87,10 @@ EQL_POOL="${XPATH_ELEMENTS[1]:-$EQL_POOL}"
 EQL_USER="${XPATH_ELEMENTS[2]:-$EQL_USER}"
 EQL_PASS="${XPATH_ELEMENTS[3]:-$EQL_PASS}"
 
-#-------------------------------------------------------------------------------
-# Retrieve volume and IQN from iscsi discovery database if not persistent
-# Equallogic generates IQN with random numbers when cloning source image (not stored in VM template)
-# If persistent, get them from VM template
-#-------------------------------------------------------------------------------
+# Adjust source volume name if not persistent
 if [ -z "$PERSISTENT" ]; then
-    SRC=$SRC-$VMID
-    EQL_VOLUME="$(eql_src_get_volume $SRC)"
-    IQN="$(eqliscsi_get_iqn_client $EQL_VOLUME)"
-else
-    IQN="$(eql_src_get_iqn $SRC)"
-    EQL_VOLUME="$(eql_src_get_volume $SRC)"
+    EQL_VOLUME="$EQL_VOLUME-$VMID"
 fi
-
 
 #-------------------------------------------------------------------------------
 # Remove directory if dst_path is a directory
@@ -109,43 +98,38 @@ fi
 
 if [ `is_disk $DST_PATH` -eq 0 ]; then
     # Directory
-    log "Deleting $DST_PATH"
-    eql_ssh_exec_and_log "$DST_HOST" "rm -rf $DST_PATH" \
-	"Error deleting $DST_PATH" \
-	"exit"
+    eql_log "Deleting $DST_PATH"
+    ssh_exec_and_log "$DST_HOST" "rm -rf $DST_PATH" "Error deleting $DST_PATH"
     exit 0
 fi
 
 #-------------------------------------------------------------------------------
 # Logout from the iSCSI target in the hypervisor
 #-------------------------------------------------------------------------------
-
 LOGOUT_CMD=$(cat <<EOF
     set -e
-    $SUDO $(eqliscsi_logout "$IQN")
+    IQN=\$($SUDO $(eqliscsi_get_iqn_from_node "$EQL_VOLUME"))
+    $SUDO $(eqliscsi_logout "\$IQN")
 EOF
 )
 
-eql_ssh_exec_and_log "$DST_HOST" "$LOGOUT_CMD" \
-    "Error logging out $DST_HOST:$IQN" \
-    "exit"
+eql_log "Logging out $DST_HOST $LOGOUT_CMD"
+ssh_exec_and_log "$DST_HOST" "$LOGOUT_CMD" "Error logging out $DST_HOST:$IQN"
 
 #-------------------------------------------------------------------------------
 # Remove target volume in the Equallogic
 #-------------------------------------------------------------------------------
 
 # Don't delete if persistent
-if [ "$PERSISTENT" = "YES" ]; then
-    exit 0
+if [ -z "$PERSISTENT" ]; then
+    # Remote volume remove on Equallogic
+    eql_log "Removing volume $EQL_VOLUME from $EQL_HOST"
+    RETVAL=$(eqladm_target_delete $EQL_VOLUME)
+    RC=$?
+    if [ "$RC" -ne 0 ]; then
+	eql_error_message "Error deleting volume $EQL_VOLUME on $EQL_HOST $RETVAL"
+	exit 1
+    fi
+    eql_log "Volume $EQL_VOLUME removed from $EQL_HOST"
 fi
-
-# Remote volume remove on Equallogic
-log "Removing volume $IQN from $EQL_HOST"
-RETVAL=$(eqladm_target_delete $EQL_VOLUME)
-ERROR=$?
-if [ "$ERROR" -ne 0 ]; then
-    log_error "Error deleting volume $EQL_VOLUME on $EQL_HOST $RETVAL"
-    exit 1
-fi
-
 exit 0
diff --git a/tm/eqliscsi/ln b/tm/eqliscsi/ln
--- a/tm/eqliscsi/ln
+++ b/tm/eqliscsi/ln
@@ -19,7 +19,7 @@
 # limitations under the License.                                             #
 #--------------------------------------------------------------------------- #
 
-# ln fe:SOURCE host:remote_system_ds/disk.i size vmid dsid
+# ln fe:SOURCE host:remote_system_ds/disk.i vm_id ds_id
 #   - fe is the front-end hostname
 #   - SOURCE is the path of the disk image in the form DS_BASE_PATH/disk
 #   - host is the target host to deploy the VM
@@ -41,42 +41,72 @@ fi
 
 . $TMCOMMON
 
+EQL_MAD_DEBUG=1
 TM_PATH=$(dirname $0)
 source ${TM_PATH}/../../datastore/eqliscsi/eqliscsi.conf
 source ${TM_PATH}/../../scripts_eqliscsi.sh
 
 #-------------------------------------------------------------------------------
-# Set dst path and dir
+# Get EQL_HOST from datastore/image
 #-------------------------------------------------------------------------------
-
-EQL_HOST="$(eql_src_get_host $SRC)"
-IQN="$(eql_src_get_iqn $SRC)"
-EQL_DEV="$EQL_BASE_DEVICE/$(eql_src_get_volume $SRC)"
-
+# Set dst path and dir
 DST_PATH=`arg_path $DST`
 DST_HOST=`arg_host $DST`
 DST_DIR=`dirname $DST_PATH`
 
+# Get disk id from DST path
+DISK_ID=$(echo "$DST_PATH" | $AWK -F. '{print $NF}')
+
+# Get datastore/image data from VM disk
+XPATH="${TM_PATH}/../../datastore/xpath.rb --stdin"
+
+unset i XPATH_ELEMENTS
+while IFS= read -r -d '' element; do
+    XPATH_ELEMENTS[i++]="$element"
+done < <(onevm show -x $VMID| $XPATH \
+                    /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/DATASTORE_ID)
+
+SRC_DSID="${XPATH_ELEMENTS[0]}"
+
+# Get EQL_HOST from datastore SRC_DSID
+unset i XPATH_ELEMENTS
+while IFS= read -r -d '' element; do
+    XPATH_ELEMENTS[i++]="$element"
+done < <(onedatastore show -x $SRC_DSID| $XPATH \
+                    /DATASTORE/TEMPLATE/EQL_HOST)
+
+EQL_HOST="${XPATH_ELEMENTS[0]:-$EQL_HOST}"
+
+# Get volume name and device
+EQL_VOLUME=$(eql_src_get_volume $SRC)
+EQL_DEV="$EQL_BASE_DEVICE/$EQL_VOLUME"
+
 # Construct command to discover target, login and link the device
-DISCOVER_CMD=$(cat <<EOF
+LINK_CMD=$(cat <<EOF
     set -e
     mkdir -p $DST_DIR
     $SUDO $(eqliscsi_discovery)
-    $SUDO $(eqliscsi_login "$IQN")
-    ERROR=\$?
-    if [ "\$ERROR" -ne 0 ]; then
-	exit \$ERROR
+    IQN=\$($SUDO $(eqliscsi_get_iqn_from_node "$EQL_VOLUME"))
+    $SUDO $(eqliscsi_login "\$IQN")
+    RC=\$?
+    if [ "\$RC" -ne 0 ]; then
+        exit \$RC
     fi
-    # poll
-    while [ ! -L "$EQL_DEV" ]; do
+    # poll 10 secs for iSCSI device
+    x=0
+    while [ "\$x" -lt 10 -a ! -L "$EQL_DEV" ]; do
+        x=\$((x+1))
         sleep 1
     done
-    ln -sf "$EQL_DEV" "$DST_PATH"
+    if [ -L "$EQL_DEV" ]; then
+	ln -sf "$EQL_DEV" "$DST_PATH"
+    else
+	echo "iSCSI device "$EQL_DEV" not found on time"
+	exit 1
+    fi
 EOF
 )
 
-eql_ssh_exec_and_log "$DST_HOST" "$DISCOVER_CMD" \
-        "Error linking $DST_HOST:$DEV" \
-	"exit"
-
+eql_log "$DST_HOST" "$LINK_CMD"
+ssh_exec_and_log "$DST_HOST" "$LINK_CMD" "Error linking $DST_HOST:$EQL_DEV"
 exit 0
diff --git a/tm/eqliscsi/mv b/tm/eqliscsi/mv
--- a/tm/eqliscsi/mv
+++ b/tm/eqliscsi/mv
@@ -40,6 +40,7 @@ fi
 
 . $TMCOMMON
 
+EQL_MAD_DEBUG=1
 TM_PATH=$(dirname $0)
 source ${TM_PATH}/../../datastore/eqliscsi/eqliscsi.conf
 source ${TM_PATH}/../../scripts_eqliscsi.sh
@@ -58,96 +59,107 @@ DST_HOST=`arg_host $DST`
 DST_DIR=`dirname $DST_PATH`
 
 if [ `is_disk $SRC_PATH` -eq 0 ]; then
-    eql_ssh_make_path $DST_HOST $DST_DIR "exit"
-
-    log "Moving $SRC to $DST"
-
-    eql_exec_and_log "$SCP -r $SRC $DST" "Could not copy $SRC to $DST" "exit"
-
-    eql_ssh_exec_and_log "$SRC_HOST" "rm -rf $SRC_PATH" \
-        "Could not remove $SRC_HOST:$SRC_PATH"
-	"exit"
-
+    ssh_make_path $DST_HOST $DST_DIR
+    eql_log "Moving $SRC to $DST"
+    exec_and_log "$SCP -r $SRC $DST" "Could not copy $SRC to $DST"
+    ssh_exec_and_log "$SRC_HOST" "rm -rf $SRC_PATH" "Could not remove $SRC_HOST:$SRC_PATH"
     exit 0
 fi
 
 if [ "$SRC" == "$DST" ]; then
-    log "Not moving $SRC to $DST, they are the same path"
-	exit 0
+    eql_log "Not moving $SRC to $DST, they are the same path"
+    exit 0
 fi
 
 #-------------------------------------------------------------------------------
 # Get image information
 #-------------------------------------------------------------------------------
 
+#-------------------------------------------------------------------------------
+# Get image information
+#-------------------------------------------------------------------------------
+# Get disk id from SRC path
+DISK_ID=$(echo "$SRC_PATH" | $AWK -F. '{print $NF}')
+
+# Get datastore/image data from VM disk
 XPATH="${TM_PATH}/../../datastore/xpath.rb --stdin"
 
 unset i XPATH_ELEMENTS
-
-DISK_ID=$(echo "$SRC_PATH" | $AWK -F. '{print $NF}')
-
 while IFS= read -r -d '' element; do
     XPATH_ELEMENTS[i++]="$element"
 done < <(onevm show -x $VMID| $XPATH \
+                    /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/DATASTORE_ID \
+                    /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/IMAGE_ID \
                     /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/SOURCE \
+                    /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/SAVE_AS \
                     /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/PERSISTENT)
 
-SRC="${XPATH_ELEMENTS[0]}"
-PERSISTENT="${XPATH_ELEMENTS[1]}"
+SRC_DSID="${XPATH_ELEMENTS[0]}"
+SRC_IMID="${XPATH_ELEMENTS[1]}"
+EQL_VOLUME="$(eql_src_get_volume ${XPATH_ELEMENTS[2]})"
+SAVE_AS="${XPATH_ELEMENTS[3]}"
+PERSISTENT="${XPATH_ELEMENTS[4]}"
 
+# Adjust source volume name if not persistent
 if [ -z "$PERSISTENT" ]; then
-    SRC=$SRC-$VMID
+    EQL_VOLUME=$EQL_VOLUME-$VMID
 fi
 
-EQL_HOST="$(eql_src_get_host $SRC)"
-IQN="$(eql_src_get_iqn $SRC)"
-EQL_VOLUME="$(eql_src_get_volume $SRC)"
-EQL_DEV="$EQL_BASE_DEVICE/$EQL_VOLUME"
-
-#-------------------------------------------------------------------------------
-# Logout from SRC_HOST
-#-------------------------------------------------------------------------------
-
-if is_iscsi "$SRC_HOST"; then
-    log "Logging out of $SRC_PATH in $SRC_HOST"
-
-    LOGOUT_CMD=$(cat <<EOF
+# Volume logout at host
+LOGOUT_CMD=$(cat <<EOF
     set -e
-    $SUDO $(eqliscsi_logout "$IQN")
+    IQN=\$($SUDO $(eqliscsi_get_iqn_from_node "$EQL_VOLUME"))
+    $SUDO $(eqliscsi_logout "\$IQN")
 EOF
 )
 
-    eql_ssh_exec_and_log "$SRC_HOST" "$LOGOUT_CMD" \
-        "Error logging out $SRC_HOST:$SRC_PATH" \
-	"exit"
+if is_iscsi "$SRC_HOST"; then
+    eql_log "Logging out $EQL_VOLUME at $SRC_HOST $LOGOUT_CMD"
+    ssh_exec_and_log "$SRC_HOST" "$LOGOUT_CMD" "Error logging out $IQN"
 fi
 
 #-------------------------------------------------------------------------------
 # Login to DST_HOST
 #-------------------------------------------------------------------------------
 if is_iscsi "$DST_HOST"; then
-    log "Logging in to $IQN in $DST_HOST"
+    # Get EQL_HOST from datastore SRC_DSID
+    unset i XPATH_ELEMENTS
+    while IFS= read -r -d '' element; do
+	XPATH_ELEMENTS[i++]="$element"
+    done < <(onedatastore show -x $SRC_DSID| $XPATH \
+	                /DATASTORE/TEMPLATE/EQL_HOST)
 
-    LOGIN_CMD=$(cat <<EOF
+    EQL_HOST="${XPATH_ELEMENTS[0]:-$EQL_HOST}"
+    EQL_DEV="$EQL_BASE_DEVICE/$EQL_VOLUME"
+
+    # Construct command to discover target, login and link the device
+    LINK_CMD=$(cat <<EOF
 	set -e
 	mkdir -p $DST_DIR
 	$SUDO $(eqliscsi_discovery)
-	$SUDO $(eqliscsi_login "$IQN")
-        ERROR=\$?
-	if [ "\$ERROR" -ne 0 ]; then
-    	    exit \$ERROR
+	IQN=\$($SUDO $(eqliscsi_get_iqn_from_node "$EQL_VOLUME"))
+	$SUDO $(eqliscsi_login "\$IQN")
+	RC=\$?
+	if [ "\$RC" -ne 0 ]; then
+	    exit \$RC
 	fi
-	# poll
-	while [ ! -L "$EQL_DEV" ]; do
+	# poll 10 secs for iSCSI device
+	x=0
+	while [ "\$x" -lt 10 -a ! -L "$EQL_DEV" ]; do
+	    x=\$((x+1))
 	    sleep 1
 	done
-	ln -sf "$EQL_DEV" "$DST_PATH"
+	if [ -L "$EQL_DEV" ]; then
+	    ln -sf "$EQL_DEV" "$DST_PATH"
+	else
+	    echo "iSCSI device "$EQL_DEV" not found on time"
+	    exit 1
+	fi
 EOF
 )
 
-    eql_ssh_exec_and_log "$DST_HOST" "$LOGIN_CMD" \
-        "Error logging in $EQL_HOST:$IQN" \
-	"exit"
+    eql_log "$DST_HOST" "$LINK_CMD"
+    ssh_exec_and_log "$DST_HOST" "$LINK_CMD" "Error linking $DST_HOST:$EQL_DEV"
 fi
 
 exit 0
diff --git a/tm/eqliscsi/postmigrate b/tm/eqliscsi/postmigrate
--- a/tm/eqliscsi/postmigrate
+++ b/tm/eqliscsi/postmigrate
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
 # -------------------------------------------------------------------------- #
 # Copyright 2014, Asociacion Clubs Baloncesto (acb.com)                      #
@@ -18,13 +18,16 @@
 # See the License for the specific language governing permissions and        #
 # limitations under the License.                                             #
 #--------------------------------------------------------------------------- #
-# POSTMIGRATE SOURCE DST remote_system_dir vmid dsid template
+# POSTMIGRATE SOURCE DST template vmid dsid remote_system_dir disk_id src_dsid persistent
 #  - SOURCE is the host where the VM is running
 #  - DST is the host where the VM is to be migrated
-#  - remote_system_dir is the path for the VM home in the system datastore
+#  - template is the template of the VM in XML and base64 encoded
 #  - vmid is the id of the VM
 #  - dsid is the target datastore
-#  - template is the template of the VM in XML and base64 encoded
+#  - remote_system_dir is the path for the VM home in the system datastore
+#  - disk_id is the DISK ID from the VM
+#  - src_dsid is the DATASTORE ID of the VM disk
+#  - persistent YES if disk image is persistent. Empty otherwise
 
 # To access the vm_template you can use the xpath.rb utility. Check the
 # datastore drivers for an example.
@@ -39,7 +42,7 @@ fi
 
 . $TMCOMMON
 
-
+EQL_MAD_DEBUG=1
 TM_PATH=$(dirname $0)
 source ${TM_PATH}/../../datastore/eqliscsi/eqliscsi.conf
 source ${TM_PATH}/../../scripts_eqliscsi.sh
@@ -48,45 +51,53 @@ source ${TM_PATH}/../../scripts_eqliscsi.sh
 
 SRC_HOST=$1
 DST_HOST=$2
-VM_PATH=$3
+TEMPLATE=$3
 
 VMID=$4
 DSID=$5
 
-TEMPLATE=$6
-
-PERSISTENT=$7
+VM_PATH=$6
+DISK_ID=$7
+SRC_DSID=$8
+PERSISTENT=$9
 
 #-------------------------------------------------------------------------------
-# Retrieve volume and IQN from iscsi discovery database if not persistent
-# Equallogic generates IQN with random numbers when cloning source image (not stored in VM template)
-# If persistent, get them from VM template
+# Get EQL_HOST from datastore SRC_DSID
 #-------------------------------------------------------------------------------
-EQL_HOST="$(eql_src_get_host $VM_PATH)"
+XPATH="${TM_PATH}/../../datastore/xpath.rb --stdin"
+
+unset i XPATH_ELEMENTS
+while IFS= read -r -d '' element; do
+    XPATH_ELEMENTS[i++]="$element"
+done < <(onedatastore show -x $SRC_DSID| $XPATH \
+                    /DATASTORE/TEMPLATE/EQL_HOST)
+
+EQL_HOST="${XPATH_ELEMENTS[0]:-$EQL_HOST}"
+
+#-------------------------------------------------------------------------------
+# Retrieve volume name and device
+#-------------------------------------------------------------------------------
 EQL_VOLUME="$(eql_src_get_volume $VM_PATH)"
-
+# If not persistent, complete volume name
 if [ -z "$PERSISTENT" ]; then
     EQL_VOLUME=$EQL_VOLUME-$VMID
-    IQN="$(eqliscsi_get_iqn_client $EQL_VOLUME)"
-else
-    IQN="$(eql_src_get_iqn $VM_PATH)"
 fi
+EQL_DEV="$EQL_BASE_DEVICE/$EQL_VOLUME"
 
 # Construct command to discover target and login
-log "Logging out of $IQN in $SRC_HOST"
+eql_log "Logging out $EQL_VOLUME at $DST_HOST"
 
-DISCOVER_CMD=$(cat <<EOF
+LOGOUT_CMD=$(cat <<EOF
     set -e
-    $SUDO $(eqliscsi_logout "$IQN")
-    ERROR=\$?
-    if [ "\$ERROR" -ne 0 ]; then
-        exit \$ERROR
+    IQN=\$($SUDO $(eqliscsi_get_iqn_from_node "$EQL_VOLUME"))
+    $SUDO $(eqliscsi_logout "\$IQN")
+    RC=\$?
+    if [ "\$RC" -ne 0 ]; then
+        exit \$RC
     fi
 EOF
 )
 
-eql_ssh_exec_and_log "$SRC_HOST" "$DISCOVER_CMD" \
-        "Error logging out $SRC_HOST:$IQN" \
-        "exit"
-
+eql_log "$DST_HOST" "$LOGOUT_CMD"
+ssh_exec_and_log "$DST_HOST" "$LOGOUT_CMD" "Log out error at $DST_HOST:$IQN"
 exit 0
